import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import TopBanner from '../components/home/TopBanner'
import NavBar from '../components/NavBar'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main className={styles.main}>
        <TopBanner />
        <div className={styles.itemsContainer}>
          <div className={styles.item}>
            <div className={styles.iconContainer}>
              <img src="/icons/book.svg" />
            </div>
            <span className={styles.viewAll}>View All</span>
            <div className={styles.itemBody}>
              <span className={styles.itemNumber}>16</span>
              <span className={styles.itemDescription}>
                Completed <br /> Assignments
              </span>
            </div>
            <img src="/assets/item1.png" className={styles.itemImage} />
          </div>
          <div className={styles.item} style={{ background: '#f9eaec' }}>
            <div className={styles.iconContainer}>
              <img src="/icons/play-circle.svg" />
            </div>
            <span className={styles.viewAll}>View All</span>
            <div className={styles.itemBody}>
              <span className={styles.itemNumber} style={{ color: '#DD0E31' }}>
                8
              </span>
              <span className={styles.itemDescription}>
                Missing <br /> Assignments
              </span>
            </div>
            <img src="/assets/item2.png" className={styles.itemImage} />
          </div>
          <div className={styles.item} style={{ background: '#dfeee3' }}>
            <div className={styles.iconContainer}>
              <img src="/icons/book-open.svg" />
            </div>
            <span className={styles.viewAll}>View All</span>
            <div className={styles.itemBody}>
              <span className={styles.itemNumber} style={{ color: '#009416' }}>
                16
              </span>
              <span className={styles.itemDescription}>
                Completed <br /> Assignments
              </span>
            </div>
            <img src="/assets/item3.png" className={styles.itemImage} />
          </div>
        </div>
      </main>
    </div>
  )
}

export default Home
